name: Déploiement sur Firebase Hosting, environnement de production
'on':
  release:
    types:
      - published
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build de l'application
        run: npm ci && npm run build

      - name: Déploiement sur l'environnement de Staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TP_DEVOPS }}"
          channelId: live
          projectId: cloudbytes-prod
          target: tp-devops
