name: Déploiement sur Firebase Hosting, environnement de Staging
'on':
  push:
    branches:
      - develop
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installation des packages
        run: npm ci

      - name: Lancement des tests
        run: npm test

      - name: Déploiement sur l'environnement de Staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TP_DEVOPS }}"
          channelId: live
          projectId: cloudbytes-prod
          target: stagingtp-devops
