name: Déploiement sur Firebase Hosting, environnement de Staging
'on':
  push:
    branches:
      - develop
jobs:
  install_dependencies_and_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installation des packages
        run: npm ci

      - name: Lancement des tests unitaires
        run: npm test

  sonarcloud_test:
    needs: install_dependencies_and_unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_on_firebase:
    needs: [install_dependencies_and_unit_test, sonarcloud_test]
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement sur l'environnement de Staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TP_DEVOPS }}"
          channelId: live
          projectId: tp-devops
          target: stagingenv-tp-devops
